export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const ADD_SEARCH_LIST_START = 'ADD_SEARCH_LIST_START';
export const ADD_SEARCH_LIST_SUCCESS = 'ADD_SEARCH_LIST_SUCCESS';
export const ADD_SEARCH_LIST_FAILURE = 'ADD_SEARCH_LIST_FAILURE';
export const DELETE_SEARCH_LIST = 'DELETE_SEARCH_LIST';
